<template>
  <div class="p-4 space-y-4">
    <!-- 1. orientation×size: по записям (10) -->
    <div class="flex flex-wrap gap-4 items-start">
      <div class="w-full max-w-3xl"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="horizontal" size="xs" /></div>
      <div class="w-full max-w-3xl"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="horizontal" size="sm" /></div>
      <div class="w-full max-w-3xl"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="horizontal" size="md" /></div>
      <div class="w-full max-w-3xl"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="horizontal" size="lg" /></div>
      <div class="w-full max-w-3xl"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="horizontal" size="xl" /></div>
      <div class="w-64"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="vertical" size="xs" /></div>
      <div class="w-64"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="vertical" size="sm" /></div>
      <div class="w-64"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="vertical" size="md" /></div>
      <div class="w-64"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="vertical" size="lg" /></div>
      <div class="w-64"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="vertical" size="xl" /></div>
    </div>
    <!-- 2. color (7) -->
    <div class="flex flex-wrap gap-4 items-start">
      <div class="w-full max-w-3xl"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="primary" /></div>
      <div class="w-full max-w-3xl"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="secondary" /></div>
      <div class="w-full max-w-3xl"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="success" /></div>
      <div class="w-full max-w-3xl"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="info" /></div>
      <div class="w-full max-w-3xl"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="warning" /></div>
      <div class="w-full max-w-3xl"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="error" /></div>
      <div class="w-full max-w-3xl"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="neutral" /></div>
    </div>
    <!-- 3. контент (дефолт) -->
    <div class="flex flex-wrap gap-4 items-start">
      <div class="w-full max-w-3xl"><UStepper :items="[{ title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" /></div>
    </div>
  </div>
</template>
