<template>
  <div class="p-4 space-y-4">
    <!-- 1. color×reverse: по записям (14) -->
    <div class="flex flex-wrap gap-4 items-start">
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="primary" /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="secondary" /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="success" /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="info" /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="warning" /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="error" /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="neutral" /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="primary" reverse /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="secondary" reverse /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="success" reverse /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="info" reverse /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="warning" reverse /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="error" reverse /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" color="neutral" reverse /></div>
    </div>
    <!-- 2. orientation×size: по записям (18) -->
    <div class="flex flex-wrap gap-4 items-start">
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="vertical" size="3xs" /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="vertical" size="2xs" /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="vertical" size="xs" /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="vertical" size="sm" /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="vertical" size="md" /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="vertical" size="lg" /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="vertical" size="xl" /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="vertical" size="2xl" /></div>
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="vertical" size="3xl" /></div>
      <div class="w-full max-w-3xl"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="horizontal" size="3xs" /></div>
      <div class="w-full max-w-3xl"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="horizontal" size="2xs" /></div>
      <div class="w-full max-w-3xl"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="horizontal" size="xs" /></div>
      <div class="w-full max-w-3xl"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="horizontal" size="sm" /></div>
      <div class="w-full max-w-3xl"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="horizontal" size="md" /></div>
      <div class="w-full max-w-3xl"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="horizontal" size="lg" /></div>
      <div class="w-full max-w-3xl"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="horizontal" size="xl" /></div>
      <div class="w-full max-w-3xl"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="horizontal" size="2xl" /></div>
      <div class="w-full max-w-3xl"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" orientation="horizontal" size="3xl" /></div>
    </div>
    <!-- 3. контент (дефолт) -->
    <div class="flex flex-wrap gap-4 items-start">
      <div class="w-64"><UTimeline :items="[{ date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-home' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-user' }, { date: '2026-01-15', title: 'Title', description: 'Description text for the parity testbed.', icon: 'i-lucide-settings' }]" :default-value="1" /></div>
    </div>
  </div>
</template>
