<template>
  <div class="p-4 space-y-4">
    <!-- 1. color×selected: по записям (7) -->
    <div class="flex flex-wrap gap-4 items-start">
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user' }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" :default-value="{ label: 'Label' }" color="primary" /></div>
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user' }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" :default-value="{ label: 'Label' }" color="secondary" /></div>
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user' }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" :default-value="{ label: 'Label' }" color="success" /></div>
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user' }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" :default-value="{ label: 'Label' }" color="info" /></div>
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user' }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" :default-value="{ label: 'Label' }" color="warning" /></div>
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user' }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" :default-value="{ label: 'Label' }" color="error" /></div>
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user' }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" :default-value="{ label: 'Label' }" color="neutral" /></div>
    </div>
    <!-- 2. disabled×selected: по записям (1) — сама запись {selected:false,disabled:false} только hover:, статически не проверяется; ячейка показывает вариант disabled (variants.disabled.true) -->
    <div class="flex flex-wrap gap-4 items-start">
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user', disabled: true }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" /></div>
    </div>
    <!-- 3. size (5) -->
    <div class="flex flex-wrap gap-4 items-start">
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user' }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" size="xs" /></div>
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user' }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" size="sm" /></div>
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user' }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" size="md" /></div>
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user' }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" size="lg" /></div>
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user' }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" size="xl" /></div>
    </div>
    <!-- 4. контент: вложенные раскрытые (дефолт); выбранный -->
    <div class="flex flex-wrap gap-4 items-start">
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user' }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" /></div>
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user' }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" :default-value="{ label: 'Label' }" /></div>
    </div>
    <!-- поправка контроллера: tree.virtualize -->
    <div class="flex flex-wrap gap-4 items-start">
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home', defaultExpanded: true, children: [{ label: 'Profile', icon: 'i-lucide-user' }, { label: 'Settings', icon: 'i-lucide-settings' }] }, { label: 'Favorites', icon: 'i-lucide-star', defaultExpanded: true, children: [{ label: 'Mail', icon: 'i-lucide-mail' }] }, { label: 'Label', icon: 'i-lucide-rocket' }]" :virtualize="false" /></div>
      <div class="w-64"><UTree :items="[{ label: 'Home', icon: 'i-lucide-home' }, { label: 'Favorites', icon: 'i-lucide-star' }, { label: 'Label', icon: 'i-lucide-rocket' }]" virtualize /></div>
    </div>
  </div>
</template>
